services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    # --- ДОБАВЬТЕ ЭТИ СТРОКИ СЮДА ---
    dns:
      - 8.8.8.8
      - 8.8.4.4
    # --------------------------------
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=db
      - DB_NAME=bot_db
      - DB_USER=bot_user
      - DB_PASSWORD=bot_pass
    ports:
      - "8080:8080"

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=bot_db
      - POSTGRES_USER=bot_user
      - POSTGRES_PASSWORD=bot_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
